server:
  http:
    addr: 0.0.0.0:8082
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:13306)/db2
  redis:
    addr: 127.0.0.1:16379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2023-12-10"
  machine_id: 1
